FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.worker.txt .
RUN pip install --no-cache-dir -r requirements.worker.txt

COPY app ./app
COPY worker.py ./worker.py

CMD ["python", "worker.py"]
