import Foundation

public struct PlaylistTrack: Codable, Identifiable {
    public let id: UUID
    public let trackId: String
    public let title: String
    public let artist: String
    public let imageUrl: String?
    public let playlistItemId: Int64? // DB row id for deletion
    
    public init(id: UUID = UUID(), trackId: String = "", title: String, artist: String, imageUrl: String? = nil, playlistItemId: Int64? = nil) {
        self.id = id
        self.trackId = trackId
        self.title = title
        self.artist = artist
        self.imageUrl = imageUrl
        self.playlistItemId = playlistItemId
    }
}

public struct PlaylistData: Codable, Identifiable {
    public let id: UUID
    public var title: String
    public var tags: String
    public var imageUrl: String?
    public var imageData: Data?
    public var tracks: [PlaylistTrack]
    public var createdAt: Date
    public var isPublic: Bool
    public var isSelectedForDeletion: Bool = false
    
    public var trackCount: Int {
        return tracks.count
    }
    
    public init(id: UUID = UUID(), 
                title: String, 
                tags: String, 
                imageUrl: String? = nil, 
                imageData: Data? = nil, 
                tracks: [PlaylistTrack] = [], 
                createdAt: Date = Date(), 
                isPublic: Bool = false) {
        self.id = id
        self.title = title
        self.tags = tags
        self.imageUrl = imageUrl
        self.imageData = imageData
        self.tracks = tracks
        self.createdAt = createdAt
        self.isPublic = isPublic
    }
}

public struct DBPlaylist: Codable {
    public let id: UUID
    public let userId: UUID
    public let name: String
    public let description: String?
    public let coverImageUrl: String?
    public let isPublic: Bool
    public let createdAt: Date
    public let updatedAt: Date
    
    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case name
        case description
        case coverImageUrl = "cover_image_url"
        case isPublic = "is_public"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

public struct DBPlaylistItem: Codable {
    public let id: Int64
    public let playlistId: UUID
    public let userId: UUID
    public let trackId: String
    public let trackTitle: String
    public let artistName: String
    public let sheetScanId: Int64?
    public let position: Int
    public let addedAt: Date
    
    enum CodingKeys: String, CodingKey {
        case id
        case playlistId = "playlist_id"
        case userId = "user_id"
        case trackId = "track_id"
        case trackTitle = "track_title"
        case artistName = "artist_name"
        case sheetScanId = "sheet_scan_id"
        case position
        case addedAt = "added_at"
    }
}

/// Insert-only model (no id/addedAt — generated by the DB)
public struct DBPlaylistItemInsert: Codable {
    public let playlistId: UUID
    public let userId: UUID
    public let trackId: String
    public let trackTitle: String
    public let artistName: String
    public let sheetScanId: Int64?
    public let position: Int
    
    enum CodingKeys: String, CodingKey {
        case playlistId = "playlist_id"
        case userId = "user_id"
        case trackId = "track_id"
        case trackTitle = "track_title"
        case artistName = "artist_name"
        case sheetScanId = "sheet_scan_id"
        case position
    }
}

// MARK: - Upload Scan Item (shared model for the picker)

/// A lightweight representation of a user's uploaded scan, used for playlist-track selection.
public struct UploadScanItem {
    public let id: Int64
    public let title: String       // derived from json_data["title"] or original_filename
    public let fileType: String    // "PDF" / "FILE"
    public let dateString: String  // formatted date
    public let sizeString: String  // formatted file size

    public init(id: Int64, title: String, fileType: String, dateString: String, sizeString: String) {
        self.id = id
        self.title = title
        self.fileType = fileType
        self.dateString = dateString
        self.sizeString = sizeString
    }
}
